import { sql, type SQL } from 'drizzle-orm';
import { timestamp, uuid, type AnyPgColumn } from 'drizzle-orm/pg-core';
import { newId } from '../id.js';

/**
 * Column fragments every table shares (STANDARDS §1.3).
 *
 * `created_at`/`updated_at` default to `now()` in the database so a raw SQL
 * insert (migration, psql, seed) is never missing them. `updated_at` is set
 * explicitly by the repository layer on every update; there is no trigger,
 * because FS §7.1 uses `updated_at` as the optimistic-concurrency token and a
 * trigger would hide who moved it.
 */

/** UUID v7 primary key, generated by the application (see `newId`). */
export const idColumn = () => uuid('id').primaryKey().$defaultFn(newId);

/** `created_at` and `updated_at`, both `timestamptz not null default now()`. */
export const timestampColumns = () => ({
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow(),
});

/**
 * `created_at` only. Used by the append-only event tables, which have no
 * `updated_at` by decision CL-E19, and by the pure join tables.
 */
export const createdAtColumn = () =>
  timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull().defaultNow();

/** Nullable soft-delete marker on `board`, `list` and `card` (CL-A2). */
export const archivedAtColumn = () =>
  timestamp('archived_at', { withTimezone: true, mode: 'date' });

/**
 * `column in ('a', 'b', …)` for a CHECK constraint, built from the single
 * `flowboard-shared` enum that defines the vocabulary (STANDARDS §1.2).
 * Adding a value to the enum therefore changes the constraint in the next
 * generated migration rather than letting the two drift apart.
 */
export function inList(column: AnyPgColumn, values: readonly string[]): SQL {
  // The values must be inlined, not bound: `drizzle-kit generate` serialises
  // this expression into the migration file, and a bound parameter would be
  // written there as a literal `$1` placeholder.
  const literals = values.map((value) => `'${value.replaceAll("'", "''")}'`).join(', ');

  return sql`${column} in ${sql.raw(`(${literals})`)}`;
}
